// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZlhj6dAmEH8JF49TYgE6uVX1bpduxZqQ',
    appId: '1:1055741880730:web:2c21d39859ae4fe6dab223',
    messagingSenderId: '1055741880730',
    projectId: 'inext-c92e4',
    authDomain: 'inext-c92e4.firebaseapp.com',
    storageBucket: 'inext-c92e4.appspot.com',
    measurementId: 'G-3JB0LWK2LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6XwcI8QYaEz1bvkrSOQIMovqpba9uTsE',
    appId: '1:1055741880730:android:971d5db171146c70dab223',
    messagingSenderId: '1055741880730',
    projectId: 'inext-c92e4',
    storageBucket: 'inext-c92e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB2ViSPozG4coTeXYJhiN44GGxlCTxSk8',
    appId: '1:1055741880730:ios:b2190127326d6d32dab223',
    messagingSenderId: '1055741880730',
    projectId: 'inext-c92e4',
    storageBucket: 'inext-c92e4.appspot.com',
    iosBundleId: 'com.example.inext',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB2ViSPozG4coTeXYJhiN44GGxlCTxSk8',
    appId: '1:1055741880730:ios:f91f43feecadd0b7dab223',
    messagingSenderId: '1055741880730',
    projectId: 'inext-c92e4',
    storageBucket: 'inext-c92e4.appspot.com',
    iosBundleId: 'com.example.inext.RunnerTests',
  );
}
